// GENERATED FILE — do not hand-edit. Run `npm run refresh:vulndb` to
// regenerate (see scripts/refreshVulnDb.ts). Source: OSV.dev advisories
// classified as malicious, for the packages in MALWARE_WATCHLIST and
// TRACKED_PACKAGES. Generated: 2026-10-04T08:07:32.830Z

export interface MaliciousDbEntry {
  packageName: string;
  id: string;
  summary: string;
  /** Exact malicious versions, or ['*'] when every version is. */
  versions: readonly string[];
  /** Malicious ranges, `[introduced, fixed)`; `fixed` null when open-ended. */
  ranges: ReadonlyArray<{ introduced: string; fixed: string | null }>;
}

/** Known-malicious package versions, matched exactly by CHAP-SUP-007 (PROPOSED_FIXES.md 3.5). */
export const MALICIOUS_DB: readonly MaliciousDbEntry[] = [
  {
    packageName: 'axios',
    id: 'MAL-2026-2307',
    summary: 'Malicious code in axios (npm)',
    versions: ['0.30.4', '1.14.1'],
    ranges: [],
  },
  {
    packageName: 'event-stream',
    id: 'GHSA-mh6f-8j2x-4483',
    summary: 'Critical severity vulnerability that affects event-stream and flatmap-stream',
    versions: ['3.3.6'],
    ranges: [{ introduced: '3.3.6', fixed: '4.0.0' }],
  },
  {
    packageName: 'flatmap-stream',
    id: 'GHSA-9x64-5r7x-2q53',
    summary: 'Malicious Package in flatmap-stream',
    versions: ['0.1.1'],
    ranges: [],
  },
  {
    packageName: 'flatmap-stream',
    id: 'GHSA-mh6f-8j2x-4483',
    summary: 'Critical severity vulnerability that affects event-stream and flatmap-stream',
    versions: ['*'],
    ranges: [],
  },
  {
    packageName: 'flatmap-stream',
    id: 'MAL-2025-20690',
    summary: 'Malicious code in flatmap-stream (npm)',
    versions: ['*'],
    ranges: [],
  },
  {
    packageName: 'ua-parser-js',
    id: 'GHSA-pjwm-rvh2-c87w',
    summary: 'Embedded malware in ua-parser-js',
    versions: ['0.7.29'],
    ranges: [{ introduced: '0.7.29', fixed: '0.7.30' }],
  },
  {
    packageName: 'coa',
    id: 'GHSA-73qr-pfmq-6rp8',
    summary: 'Embedded malware in coa',
    versions: ['2.0.3'],
    ranges: [],
  },
  {
    packageName: 'rc',
    id: 'GHSA-g2q5-5433-rhrf',
    summary: 'Embedded malware in rc',
    versions: ['1.2.9'],
    ranges: [],
  },
  {
    packageName: 'node-ipc',
    id: 'GHSA-97m3-w2cp-4xx6',
    summary: 'Embedded Malicious Code in node-ipc',
    versions: [],
    ranges: [{ introduced: '10.1.1', fixed: '10.1.3' }],
  },
  {
    packageName: 'node-ipc',
    id: 'MAL-2026-3744',
    summary: 'Malicious code in node-ipc (npm)',
    versions: ['9.1.6', '9.2.3', '12.0.1'],
    ranges: [],
  },
  {
    packageName: 'eslint-scope',
    id: 'GHSA-hxxf-q3w9-4xgw',
    summary: 'Malicious Package in eslint-scope',
    versions: ['3.7.2'],
    ranges: [{ introduced: '3.7.2', fixed: '3.7.3' }],
  },
  {
    packageName: 'eslint-config-eslint',
    id: 'GHSA-hxxf-q3w9-4xgw',
    summary: 'Malicious Package in eslint-scope',
    versions: ['5.0.2'],
    ranges: [{ introduced: '5.0.2', fixed: '6.0.0' }],
  },
  {
    packageName: 'eslint-config-eslint',
    id: 'GHSA-pv55-r6j3-wp94',
    summary: 'Malicious Package in eslint-config-eslint',
    versions: ['5.0.2'],
    ranges: [],
  },
  {
    packageName: 'getcookies',
    id: 'GHSA-3cjv-4phw-gvvv',
    summary: 'Malicious Package in getcookies',
    versions: ['*'],
    ranges: [],
  },
  {
    packageName: 'getcookies',
    id: 'MAL-2025-21368',
    summary: 'Malicious code in getcookies (npm)',
    versions: ['*'],
    ranges: [],
  },
  {
    packageName: 'electron-native-notify',
    id: 'GHSA-j8qr-rvcv-crhv',
    summary: 'Malicious Package in electron-native-notify',
    versions: ['*'],
    ranges: [],
  },
  {
    packageName: 'electron-native-notify',
    id: 'MAL-2025-19452',
    summary: 'Malicious code in electron-native-notify (npm)',
    versions: ['*'],
    ranges: [],
  },
  {
    packageName: 'chalk',
    id: 'MAL-2025-46969',
    summary: 'Malicious code in chalk (npm)',
    versions: ['5.6.1'],
    ranges: [],
  },
  {
    packageName: 'debug',
    id: 'GHSA-4x49-vf9v-38px',
    summary: 'debug@4.4.2 contains malware after npm account takeover',
    versions: ['4.4.2'],
    ranges: [{ introduced: '4.4.2', fixed: '4.4.3' }],
  },
  {
    packageName: 'debug',
    id: 'MAL-2025-46974',
    summary: 'Malicious code in debug (npm)',
    versions: ['4.4.2'],
    ranges: [],
  },
  {
    packageName: 'ansi-styles',
    id: 'MAL-2025-46967',
    summary: 'Malicious code in ansi-styles (npm)',
    versions: ['6.2.2'],
    ranges: [],
  },
  {
    packageName: 'ansi-regex',
    id: 'MAL-2025-46966',
    summary: 'Malicious code in ansi-regex (npm)',
    versions: ['6.2.1'],
    ranges: [],
  },
  {
    packageName: 'strip-ansi',
    id: 'MAL-2025-46980',
    summary: 'Malicious code in strip-ansi (npm)',
    versions: ['7.1.1'],
    ranges: [],
  },
  {
    packageName: 'supports-color',
    id: 'MAL-2025-46981',
    summary: 'Malicious code in supports-color (npm)',
    versions: ['10.2.1'],
    ranges: [],
  },
  {
    packageName: 'wrap-ansi',
    id: 'MAL-2025-46983',
    summary: 'Malicious code in wrap-ansi (npm)',
    versions: ['9.0.1'],
    ranges: [],
  },
  {
    packageName: 'color-convert',
    id: 'GHSA-pxx3-g568-hxr4',
    summary: 'color-convert@3.1.1 contains malware after npm account takeover',
    versions: ['3.1.1'],
    ranges: [{ introduced: '3.1.1', fixed: '3.1.2' }],
  },
  {
    packageName: 'color-convert',
    id: 'MAL-2025-46971',
    summary: 'Malicious code in color-convert (npm)',
    versions: ['3.1.1'],
    ranges: [],
  },
  {
    packageName: 'color-name',
    id: 'GHSA-5fvm-p68v-5wmh',
    summary: 'color-name@2.0.1 contains malware after npm account takeover',
    versions: ['2.0.1'],
    ranges: [{ introduced: '2.0.1', fixed: '2.0.2' }],
  },
  {
    packageName: 'color-name',
    id: 'MAL-2025-46972',
    summary: 'Malicious code in color-name (npm)',
    versions: ['2.0.1'],
    ranges: [],
  },
  {
    packageName: 'slice-ansi',
    id: 'MAL-2025-46979',
    summary: 'Malicious code in slice-ansi (npm)',
    versions: ['7.1.1'],
    ranges: [],
  },
  {
    packageName: 'is-arrayish',
    id: 'GHSA-frh7-2f84-v9mw',
    summary: 'is-arrayish@0.3.3 contains malware after npm account takeover',
    versions: ['0.3.3'],
    ranges: [{ introduced: '0.3.3', fixed: '0.3.4' }],
  },
  {
    packageName: 'is-arrayish',
    id: 'MAL-2025-46977',
    summary: 'Malicious code in is-arrayish (npm)',
    versions: ['0.3.3'],
    ranges: [],
  },
  {
    packageName: 'simple-swizzle',
    id: 'GHSA-9g9j-rggx-7fmg',
    summary: 'simple-swizzle@0.2.3 contains malware after npm account takeover',
    versions: ['0.2.3'],
    ranges: [{ introduced: '0.2.3', fixed: '0.2.4' }],
  },
  {
    packageName: 'simple-swizzle',
    id: 'MAL-2025-46978',
    summary: 'Malicious code in simple-swizzle (npm)',
    versions: ['0.2.3'],
    ranges: [],
  },
  {
    packageName: 'error-ex',
    id: 'GHSA-6jp5-hh4c-8c5h',
    summary: 'error-ex@1.3.3 contains malware after npm account takeover',
    versions: ['1.3.3'],
    ranges: [{ introduced: '1.3.3', fixed: '1.3.4' }],
  },
  {
    packageName: 'error-ex',
    id: 'MAL-2025-46975',
    summary: 'Malicious code in error-ex (npm)',
    versions: ['1.3.3'],
    ranges: [],
  },
  {
    packageName: 'has-ansi',
    id: 'MAL-2025-46976',
    summary: 'Malicious code in has-ansi (npm)',
    versions: ['6.0.1'],
    ranges: [],
  },
  {
    packageName: 'chalk-template',
    id: 'MAL-2025-46970',
    summary: 'Malicious code in chalk-template (npm)',
    versions: ['1.1.1'],
    ranges: [{ introduced: '1.1.1', fixed: '1.1.2' }],
  },
  {
    packageName: 'backslash',
    id: 'GHSA-53mq-f4w3-f7qv',
    summary: 'backslash@0.2.1 contains malware after npm account takeover',
    versions: ['0.2.1'],
    ranges: [{ introduced: '0.2.1', fixed: '0.2.2' }],
  },
  {
    packageName: 'backslash',
    id: 'MAL-2025-46968',
    summary: 'Malicious code in backslash (npm)',
    versions: ['0.2.1'],
    ranges: [],
  },
  {
    packageName: 'nx',
    id: 'MAL-2025-41443',
    summary: 'Malicious code in nx (npm)',
    versions: ['20.9.0', '20.10.0', '20.11.0', '20.12.0', '21.5.0', '21.6.0', '21.7.0', '21.8.0'],
    ranges: [],
  },
  {
    packageName: '@nx/devkit',
    id: 'MAL-2025-41436',
    summary: 'Malicious code in @nx/devkit (npm)',
    versions: ['20.9.0', '21.5.0'],
    ranges: [],
  },
  {
    packageName: '@nx/js',
    id: 'MAL-2025-41439',
    summary: 'Malicious code in @nx/js (npm)',
    versions: ['20.9.0', '21.5.0'],
    ranges: [],
  },
  {
    packageName: '@nx/workspace',
    id: 'MAL-2025-41442',
    summary: 'Malicious code in @nx/workspace (npm)',
    versions: ['20.9.0', '21.5.0'],
    ranges: [],
  },
  {
    packageName: '@ctrl/tinycolor',
    id: 'MAL-2025-47141',
    summary: 'Malicious code in @ctrl/tinycolor (npm)',
    versions: ['4.1.2', '4.1.1'],
    ranges: [],
  },
  {
    packageName: '@solana/web3.js',
    id: 'GHSA-jcxm-7wvp-g6p5',
    summary:
      'Modified package published to npm, containing malware that exfiltrates private key material',
    versions: [],
    ranges: [{ introduced: '1.95.6', fixed: '1.95.8' }],
  },
  {
    packageName: '@solana/web3.js',
    id: 'MAL-2024-11183',
    summary: 'Malicious code in @solana/web3.js (npm)',
    versions: [],
    ranges: [{ introduced: '1.95.6', fixed: '1.95.8' }],
  },
  {
    packageName: '@lottiefiles/lottie-player',
    id: 'MAL-2024-10301',
    summary: 'Malicious code in @lottiefiles/lottie-player (npm)',
    versions: ['2.0.5', '2.0.6', '2.0.7'],
    ranges: [],
  },
  {
    packageName: 'is',
    id: 'MAL-2025-6020',
    summary: 'Malicious code in is (npm)',
    versions: ['3.3.1', '5.0.0'],
    ranges: [],
  },
  {
    packageName: 'eslint-config-prettier',
    id: 'GHSA-f29h-pxvx-f335',
    summary:
      'eslint-config-prettier, eslint-plugin-prettier, synckit, @pkgr/core, napi-postinstall have embedded malicious code',
    versions: ['8.10.1'],
    ranges: [{ introduced: '8.10.1', fixed: '8.10.2' }],
  },
  {
    packageName: 'eslint-config-prettier',
    id: 'MAL-2025-6022',
    summary: 'Malicious code in eslint-config-prettier (npm)',
    versions: ['8.10.1', '9.1.1', '10.1.6', '10.1.7'],
    ranges: [],
  },
  {
    packageName: 'eslint-plugin-prettier',
    id: 'GHSA-f29h-pxvx-f335',
    summary:
      'eslint-config-prettier, eslint-plugin-prettier, synckit, @pkgr/core, napi-postinstall have embedded malicious code',
    versions: [],
    ranges: [{ introduced: '4.2.2', fixed: '4.2.4' }],
  },
  {
    packageName: 'eslint-plugin-prettier',
    id: 'MAL-2025-6023',
    summary: 'Malicious code in eslint-plugin-prettier (npm)',
    versions: ['4.2.2', '4.2.3'],
    ranges: [],
  },
  {
    packageName: 'synckit',
    id: 'GHSA-f29h-pxvx-f335',
    summary:
      'eslint-config-prettier, eslint-plugin-prettier, synckit, @pkgr/core, napi-postinstall have embedded malicious code',
    versions: ['0.11.9'],
    ranges: [{ introduced: '0.11.9', fixed: '0.11.10' }],
  },
  {
    packageName: 'synckit',
    id: 'MAL-2025-6026',
    summary: 'Malicious code in synckit (npm)',
    versions: ['0.11.9'],
    ranges: [],
  },
  {
    packageName: '@pkgr/core',
    id: 'GHSA-f29h-pxvx-f335',
    summary:
      'eslint-config-prettier, eslint-plugin-prettier, synckit, @pkgr/core, napi-postinstall have embedded malicious code',
    versions: ['0.2.8'],
    ranges: [{ introduced: '0.2.8', fixed: '0.2.9' }],
  },
  {
    packageName: '@pkgr/core',
    id: 'MAL-2025-6021',
    summary: 'Malicious code in @pkgr/core (npm)',
    versions: ['0.2.8'],
    ranges: [],
  },
  {
    packageName: 'napi-postinstall',
    id: 'GHSA-f29h-pxvx-f335',
    summary:
      'eslint-config-prettier, eslint-plugin-prettier, synckit, @pkgr/core, napi-postinstall have embedded malicious code',
    versions: ['0.3.1'],
    ranges: [{ introduced: '0.3.1', fixed: '0.3.2' }],
  },
  {
    packageName: 'napi-postinstall',
    id: 'MAL-2025-6025',
    summary: 'Malicious code in napi-postinstall (npm)',
    versions: ['0.3.1'],
    ranges: [],
  },
  {
    packageName: 'got-fetch',
    id: 'GHSA-f29h-pxvx-f335',
    summary:
      'eslint-config-prettier, eslint-plugin-prettier, synckit, @pkgr/core, napi-postinstall have embedded malicious code',
    versions: [],
    ranges: [{ introduced: '5.1.11', fixed: '6.0.0' }],
  },
  {
    packageName: 'got-fetch',
    id: 'MAL-2025-6024',
    summary: 'Malicious code in got-fetch (npm)',
    versions: ['5.1.11', '5.1.12'],
    ranges: [],
  },
];
